# Final notebook

In [1]:
import pandas as pd
import numpy as np
import geopandas as gpd
import optuna
from sklearn.ensemble import RandomForestRegressor
from sklearn.multioutput import MultiOutputRegressor
from sklearn.metrics import mean_squared_error
from sklearn.preprocessing import LabelEncoder
from sklearn.neighbors import KDTree

In [2]:
# Define the path to your file in the bucket
file_path = '../../original_data/ais_train.csv'

# Load the file into a pandas dataframe
baseDataset = pd.read_csv(file_path, delimiter= '|', encoding= 'utf-8')

# Display the dataframe
baseDataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1522065 entries, 0 to 1522064
Data columns (total 11 columns):
 #   Column     Non-Null Count    Dtype
---  ------     --------------    -----
 0   time       1522065 non-null  object
 1   cog        1522065 non-null  float64
 2   sog        1522065 non-null  float64
 3   rot        1522065 non-null  int64
 4   heading    1522065 non-null  int64
 5   navstat    1522065 non-null  int64
 6   etaRaw     1522065 non-null  object
 7   latitude   1522065 non-null  float64
 8   longitude  1522065 non-null  float64
 9   vesselId   1522065 non-null  object
 10  portId     1520450 non-null  object
dtypes: float64(4), int64(3), object(4)
memory usage: 127.7+ MB

In [3]:
testset = pd.read_csv('../../original_data/ais_test.csv')
testset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51739 entries, 0 to 51738
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   ID              51739 non-null  int64
 1   vesselId        51739 non-null  object
 2   time            51739 non-null  object
 3   scaling_factor  51739 non-null  float64
dtypes: float64(1), int64(1), object(2)
memory usage: 1.6+ MB

### Initial pre-processing of training set

In [4]:
def preprocess_ais_train(df):

    # Step 1: Convert 'time' to datetime and drop useless columns
    df['time'] = pd.to_datetime(df['time'], format='%Y-%m-%d %H:%M:%S')
    df.drop('etaRaw', axis=1, inplace=True)

    # Step 2: Sort by vesselId and time
    df = df.sort_values(by=['vesselId', 'time']).reset_index(drop=True)
    

    # Step 3: Convert relevant columns to float
    df['cog'] = df['cog'].astype(float)
    df['sog'] = df['sog'].astype(float)
    df['rot'] = df['rot'].astype(float)
    df['heading'] = df['heading'].astype(float)
    df['latitude'] = df['latitude'].astype(float)
    df['longitude'] = df['longitude'].astype(float)
    
    # Step 4: Replace invalid or default values with NaN
    df['cog'] = np.where((df['cog'] == 360) | (df['cog'] > 360) | (df['cog'] < 0), np.nan, df['cog'])
    df['sog'] = np.where((df['sog'] == 1023) | (df['sog'] < 0), np.nan, df['sog'])
    df['heading'] = np.where((df['heading'] > 360) | (df['heading'] == 511) | (df['heading'] < 0), np.nan, df['heading'])
    df['rot'] = np.where(df['rot'].isin([127, 128, -127, -128]), np.nan, df['rot'])

    # Step 5: Normalize 'cog' and 'heading'
    df['cog'] = (df['cog'] / 180) - 1
    df['heading'] = (df['heading'] / 180) - 1

    # Step 6: Remove all moored vessels
    """ 
    Moored vessels give little to no information about movement, and still vessel and be inferred by the model
     due to time elapsed. Hence, we remove all moored instance in light of having more informative data 
     """
    df = df[df['navstat'] != 5]

    # Step 7: Remove all rows with Nan values
    df = df.dropna()

    return df

baseDataset = preprocess_ais_train(baseDataset)

In [5]:
baseDataset.info()

<class 'pandas.core.frame.DataFrame'>
Index: 892056 entries, 0 to 1522064
Data columns (total 10 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   time       892056 non-null  datetime64[ns]
 1   cog        892056 non-null  float64
 2   sog        892056 non-null  float64
 3   rot        892056 non-null  float64
 4   heading    892056 non-null  float64
 5   navstat    892056 non-null  int64
 6   latitude   892056 non-null  float64
 7   longitude  892056 non-null  float64
 8   vesselId   892056 non-null  object
 9   portId     892056 non-null  object
dtypes: datetime64[ns](1), float64(6), int64(1), object(2)
memory usage: 74.9+ MB

In [6]:
# Get the unique vesselIds from the test set
vessel_ids_test = set(testset['vesselId'].unique())

# Get the count of records per vesselId in the training set
vessel_record_counts = baseDataset['vesselId'].value_counts()

# Get the 10 vessels with the lowest number of records
lowest_record_vessels = vessel_record_counts.nsmallest(20)

# Check if these vessels are in the test set
vessels_in_test = lowest_record_vessels.index.isin(vessel_ids_test)

# Combine the results into a dataframe for easy viewing
vessels_with_low_records = pd.DataFrame({
    'vesselId': lowest_record_vessels.index,
    'record_count': lowest_record_vessels.values,
    'in_test_set': vessels_in_test
})

# Display the result
print(vessels_with_low_records)

                    vesselId  record_count  in_test_set
0   61e9f3cbb937134a3c4bff09             1        False
1   61e9f43fb937134a3c4c016f            77        False
2   61e9f39ab937134a3c4bfdb9           138        False
3   61e9f45eb937134a3c4c0235           140        False
4   61e9f45cb937134a3c4c022b           155        False
5   61e9f47ab937134a3c4c02f7           169        False
6   61e9f42cb937134a3c4c00f9           172        False
7   61e9f3afb937134a3c4bfe47           219        False
8   61e9f3bcb937134a3c4bfe91           220         True
9   61e9f456b937134a3c4c0203           223        False
10  61e9f408b937134a3c4c0023           229        False
11  61e9f418b937134a3c4c0077           239        False
12  61e9f460b937134a3c4c0243           246        False
13  61e9f3aeb937134a3c4bfe45           252        False
14  61e9f3c3b937134a3c4bfeb7           264        False
15  61e9f3bab937134a3c4bfe8b           267        False
16  61e9f42cb937134a3c4c00fb           292        False
17  61e9f402b937134a3c4c000f           293        False
18  61e9f3f7b937134a3c4bffc5           297        False
19  61e9f409b937134a3c4c0027           302        False

In [7]:
# List of vessel IDs to remove
vessels_to_remove = ['61e9f3cbb937134a3c4bff09', '61e9f3adb937134a3c4bfe37']

# Remove vessels from the dataset
baseDataset = baseDataset[~baseDataset['vesselId'].isin(vessels_to_remove)]

In [8]:
def filter_short_intervals(data, min_time_diff_minutes= 8):

    # Ensure time column is in datetime format
    data['time'] = pd.to_datetime(data['time'])
    
    # Sort by vesselId and time to ensure proper order
    data = data.sort_values(['vesselId', 'time']).reset_index(drop=True)

    # Calculate time differences in minutes
    data['time_diff'] = data.groupby('vesselId')['time'].diff().dt.total_seconds() / 60  # in minutes

    # Filter out records with time differences less than the specified threshold
    filtered_data = data[(data['time_diff'].isna()) | (data['time_diff'] >= min_time_diff_minutes)].copy()

    # Drop the time_diff column after filtering
    filtered_data = filtered_data.drop(columns=['time_diff']).reset_index(drop=True)
    
    return filtered_data

baseDataset = filter_short_intervals(baseDataset)

In [9]:
def haversine(lat1, lon1, lat2, lon2):
    # Haversine formula to calculate the great-circle distance between two points
    R = 3440.065  # Radius of Earth in nautical miles
    lat1_rad = np.radians(lat1.astype(float))
    lon1_rad = np.radians(lon1.astype(float))
    lat2_rad = np.radians(lat2.astype(float))
    lon2_rad = np.radians(lon2.astype(float))
    
    dlat = lat2_rad - lat1_rad
    dlon = lon2_rad - lon1_rad
    
    a = np.sin(dlat / 2.0)**2 + np.cos(lat1_rad) * np.cos(lat2_rad) * np.sin(dlon / 2.0)**2
    c = 2 * np.arcsin(np.sqrt(a))
    
    return R * c

def heuristic_clean(data, vthreshold=30):
    """
    Cleans the trajectory data by removing points with unrealistic speeds.
    
    :param data: DataFrame containing raw trajectory data
    :param vthreshold: Speed threshold in knots
    :return: Cleaned trajectory DataFrame
    """
    # Drop duplicates and reset index
    data = data.drop_duplicates().reset_index(drop=True)
    
    # Sort by vessel ID and time to ensure correct order
    data = data.sort_values(by=['vesselId', 'time']).reset_index(drop=True)
    
    # Shift the columns to align with the previous record within each vessel
    data['prev_latitude'] = data.groupby('vesselId')['latitude'].shift(1)
    data['prev_longitude'] = data.groupby('vesselId')['longitude'].shift(1)
    data['prev_time'] = data.groupby('vesselId')['time'].shift(1)
    
    # Calculate time differences in hours
    data['delta_time'] = (data['time'] - data['prev_time']).dt.total_seconds() / 3600.0  # in hours
    
    # Calculate distances using the haversine function where we have valid previous points
    valid_rows = data['prev_latitude'].notna() & data['prev_longitude'].notna()
    data.loc[valid_rows, 'delta_distance'] = haversine(
        data.loc[valid_rows, 'prev_latitude'].to_numpy(),
        data.loc[valid_rows, 'prev_longitude'].to_numpy(),
        data.loc[valid_rows, 'latitude'].to_numpy(),
        data.loc[valid_rows, 'longitude'].to_numpy()
    )
    
    # Calculate speed (distance/time) and filter by threshold
    data['speed'] = data['delta_distance'] / data['delta_time']
    
    # Filter out rows where speed exceeds the threshold
    cleaned_data = data[(data['speed'] <= vthreshold) | data['speed'].isna()].copy()
    
    # Drop intermediate calculation columns
    cleaned_data = cleaned_data.drop(columns=['prev_latitude', 'prev_longitude', 'prev_time', 
                                              'delta_time', 'delta_distance', 'speed'])
    
    return cleaned_data.reset_index(drop=True)

baseDataset = heuristic_clean(baseDataset)

### Positional feature engineering

Kanskje legge til etterhvert?

"""
def calculate_movement_deltas(df):

    # Calculate time difference in seconds between consecutive points for each vessel
    df = df.sort_values(by=['vesselId', 'time']).reset_index(drop=True)
    df['time_diff'] = df.groupby('vesselId')['time'].diff().dt.total_seconds()
    
    # Convert cog to radians for trigonometric calculations
    df['cog_rad'] = np.radians(df['cog'])

    # Calculate delta_lat and delta_lon based on COG, ROT, and time difference
    df['delta_lat'] = np.sin(df['cog_rad']) * df['time_diff'] * df['sog']
    df['delta_lon'] = np.cos(df['cog_rad']) * df['time_diff'] * df['sog']

    # Fill NaN values in delta_lat and delta_lon with 0
    df['delta_lat'].fillna(0, inplace=True)
    df['delta_lon'].fillna(0, inplace=True)

    # Drop the unnecessary columns
    df.drop(columns=['cog_rad', 'time_diff'], inplace=True)

    return df

baseDataset = calculate_movement_deltas(baseDataset)
"""

In [10]:
def add_temporal_features(df):
    # Ensure 'time' column is in datetime format
    df['time'] = pd.to_datetime(df['time'])
    
    # Extract day of the week (0=Monday, 6=Sunday)
    df['day_of_week'] = df['time'].dt.dayofweek
    
    # Create a binary feature for weekends (0=Weekday, 1=Weekend)
    df['is_weekend'] = df['day_of_week'].isin([5, 6]).astype(int)
    
    # Create a boolean feature for seasons (1=Spring or Summer, 0=Winter or Autumn)
    df['month'] = df['time'].dt.month
    df['season'] = df['month'].apply(lambda x: 1 if x in [3, 4, 5, 6, 7, 8] else 0)
    
    # Drop the intermediate 'month' and 'day_of_week' columns
    df.drop(columns=['month', 'day_of_week'], inplace=True)
    
    return df

# Apply the feature engineering function to the baseDataset
baseDataset = add_temporal_features(baseDataset)

 ### Employ Port based feature

In [11]:
# Define the path to your file in the bucket
file_path = '../../original_data/ports.csv'

#Load the file into a pandas dataframe
ports = pd.read_csv(file_path, delimiter= '|', encoding= 'utf-8')

def preprocess_ports_df(ports_df):
    # Renaming the latitude and longitude columns in ports_df to portLatitude and portLongitude
    ports_df = ports_df.rename(columns={'latitude': 'portLatitude', 'longitude': 'portLongitude'})
    # List of columns to keep
    columns_to_keep = ['portId', 'portLatitude', 'portLongitude']

    # Drop all other columns except the ones specified in columns_to_keep
    ports_df = ports_df[columns_to_keep]
    return ports_df

ports = preprocess_ports_df(ports)

In [12]:
def find_close_to_port(df, ports, distance_threshold_nm=2.5, 
                       vessel_lat_col='latitude', vessel_lon_col='longitude', 
                       port_lat_col='portLatitude', port_lon_col='portLongitude'):
    """
    Determines if each vessel in df is close to a port within a specified distance (in nautical miles).

    Parameters:
    - df (DataFrame): DataFrame containing vessel data with specified latitude and longitude columns.
    - ports (DataFrame): DataFrame containing port data with specified latitude and longitude columns.
    - distance_threshold_nm (float): Distance threshold in nautical miles for identifying proximity to ports.
    - vessel_lat_col (str): Column name for the vessel latitude in df.
    - vessel_lon_col (str): Column name for the vessel longitude in df.
    - port_lat_col (str): Column name for the port latitude in ports.
    - port_lon_col (str): Column name for the port longitude in ports.

    Returns:
    - DataFrame: Updated df with a new binary column 'close_to_port', where 1 indicates proximity to a port within the threshold.
    """

    # Convert latitude and longitude to radians
    df['lat_rad'] = np.radians(df[vessel_lat_col])
    df['lon_rad'] = np.radians(df[vessel_lon_col])
    ports['lat_rad'] = np.radians(ports[port_lat_col])
    ports['lon_rad'] = np.radians(ports[port_lon_col])

    # Build a k-d tree using port coordinates
    port_coords = np.vstack((ports['lat_rad'], ports['lon_rad'])).T
    port_tree = KDTree(port_coords, metric='euclidean')  # Using 'euclidean' since we pre-convert to radians

    # Convert nautical miles to radians (1 nautical mile ≈ 1/3437.75 radians)
    distance_threshold_radians = distance_threshold_nm / 3437.75

    # Query each vessel against the port k-d tree for the closest port within the threshold
    vessel_coords = np.vstack((df['lat_rad'], df['lon_rad'])).T
    distances, indices = port_tree.query(vessel_coords, k=1, return_distance=True)

    # Update df with close_to_port information based on the distance threshold
    df['close_to_port'] = (distances.flatten() < distance_threshold_radians).astype(int)

    # Drop the temporary radian columns
    df.drop(columns=['lat_rad', 'lon_rad'], inplace=True)

    return df

"""
baseDataset = find_close_to_port(
    df=baseDataset, 
    ports=ports, 
    distance_threshold_nm=2.8, 
    vessel_lat_col='latitude', 
    vessel_lon_col='longitude', 
    port_lat_col='portLatitude', 
    port_lon_col='portLongitude'
)
"""

"\nbaseDataset = find_close_to_port(\n    df=baseDataset, \n    ports=ports, \n    distance_threshold_nm=2.8, \n    vessel_lat_col='latitude', \n    vessel_lon_col='longitude', \n    port_lat_col='portLatitude', \n    port_lon_col='portLongitude'\n)\n"

In [13]:
baseDataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 871978 entries, 0 to 871977
Data columns (total 12 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   time        871978 non-null  datetime64[ns]
 1   cog         871978 non-null  float64
 2   sog         871978 non-null  float64
 3   rot         871978 non-null  float64
 4   heading     871978 non-null  float64
 5   navstat     871978 non-null  int64
 6   latitude    871978 non-null  float64
 7   longitude   871978 non-null  float64
 8   vesselId    871978 non-null  object
 9   portId      871978 non-null  object
 10  is_weekend  871978 non-null  int64
 11  season      871978 non-null  int64
dtypes: datetime64[ns](1), float64(6), int64(3), object(2)
memory usage: 79.8+ MB

# We finalize the traning data and fill the test data

In [14]:
le = LabelEncoder()

vessels = baseDataset["vesselId"].unique().tolist()
le.fit(vessels)
baseDataset["vesselId"] = le.transform(baseDataset["vesselId"])

baseDataset = baseDataset.drop(columns=['navstat', 'portId'])

In [15]:
baseDataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 871978 entries, 0 to 871977
Data columns (total 10 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   time        871978 non-null  datetime64[ns]
 1   cog         871978 non-null  float64
 2   sog         871978 non-null  float64
 3   rot         871978 non-null  float64
 4   heading     871978 non-null  float64
 5   latitude    871978 non-null  float64
 6   longitude   871978 non-null  float64
 7   vesselId    871978 non-null  int64
 8   is_weekend  871978 non-null  int64
 9   season      871978 non-null  int64
dtypes: datetime64[ns](1), float64(6), int64(3)
memory usage: 66.5 MB

In [16]:
def fill_test_data(training_filepath, test_filepath, ports_df, le, distance_threshold_nm=3):

    # Load and process training data to get the latest known position of each vessel
    ais_train = pd.read_csv(training_filepath, sep='|')
    ais_train['time'] = pd.to_datetime(ais_train['time'])
    ais_train = ais_train.sort_values(by='time')

    ais_train = find_close_to_port(
    df=ais_train, 
    ports=ports, 
    distance_threshold_nm=2.5, 
    vessel_lat_col='latitude', 
    vessel_lon_col='longitude', 
    port_lat_col='portLatitude', 
    port_lon_col='portLongitude'
)
    
    final_positions = ais_train.groupby("vesselId").last()

    # Rename columns in final_positions for feature engineering in the test data
    final_positions = final_positions.rename(columns={
        'time': 'time_previous',
        'latitude': 'latitude_previous',
        'longitude': 'longitude_previous',
        'sog': 'sog_previous',
        'cog': 'cog_previous',
        'rot': 'rot_previous',
        'heading': 'heading_previous',
        #'close_to_port': 'close_to_port_previous'
    })

    # Load test data and merge with latest known positions
    ais_test = pd.read_csv(test_filepath)
    ais_test['time'] = pd.to_datetime(ais_test['time'])
    ais_test= ais_test.merge(final_positions, on="vesselId", how="left")

    # Normalize course and heading
    ais_test['cog_previous'] = (ais_test['cog_previous'] / 180) - 1
    ais_test['heading_previous'] = (ais_test['heading_previous'] / 180) - 1

    # Encode vessel IDs using the provided LabelEncoder
    ais_test['vesselId'] = le.transform(ais_test['vesselId'])

    # Calculate time difference in seconds between the test time and last known time
    ais_test['time_gap'] = (ais_test['time'] - ais_test['time_previous']).dt.total_seconds()

    # Temporal features
    ais_test['season'] = 0
    ais_test['is_weekend'] = 0

    testset = ais_test.drop(columns=['scaling_factor', 'time_previous', 'navstat', 'etaRaw', 'portId'])

    return testset


test_filled = fill_test_data(
    training_filepath='../../original_data/ais_train.csv',
    test_filepath='../../original_data/ais_test.csv',
    ports_df=ports,
    le=le,
    distance_threshold_nm=3,
)

In [17]:
test_filled.head(10)

,ID,vesselId,time,cog_previous,sog_previous,rot_previous,heading_previous,latitude_previous,longitude_previous,close_to_port,time_gap,season,is_weekend
0,0,83,2024-05-08 00:03:16,-0.002222,0.0,0,0.911111,31.14647,-81.49789,1,900.0,0,0
1,1,619,2024-05-08 00:06:17,-0.862778,0.0,0,0.188889,14.81694,120.29625,1,541.0,0,0
2,2,592,2024-05-08 00:10:02,-0.955556,18.7,0,-0.966667,38.27895,10.78280,0,654.0,0,0
3,3,538,2024-05-08 00:10:34,0.785000,0.1,0,-0.611111,-43.53785,172.83522,0,1080.0,0,0
4,4,1,2024-05-08 00:12:27,0.616667,0.3,0,0.527778,48.53320,-6.12003,0,1258.0,0,0
5,5,682,2024-05-08 00:12:31,-0.716667,0.0,0,-0.716667,51.35306,3.19241,1,1087.0,0,0
6,6,159,2024-05-08 00:13:58,0.903333,0.0,0,0.655556,43.34995,-8.50739,0,1077.0,0,0
7,7,90,2024-05-08 00:14:41,-0.913333,0.0,0,0.844444,51.31666,3.22506,1,1082.0,0,0
8,8,486,2024-05-08 00:15:03,0.833333,0.0,0,0.494444,40.84712,29.29052,0,1083.0,0,0
9,9,174,2024-05-08 00:15:34,0.153889,0.1,0,0.400000,38.47378,15.91582,1,1080.0,0,0

### Keep only vital information for dataset we want to create

# We create the training set!

In [18]:
def lagged_training_data(df, lag_steps):
    """
    Creates a training set with features that include previous values for latitude, longitude,
    speed over ground (sog), and time-related features like hour and day of the week.

    Parameters:
    - df (DataFrame): The input DataFrame containing the AIS data.
    - lag_steps (int): The number of time steps to shift for creating lagged features.

    Returns:
    - DataFrame: A new DataFrame with added lagged features and time-related information.
    """
    # Create a copy of the input DataFrame to work on
    data = df.copy()

    # Generate lagged features for latitude, longitude, and speed over ground (sog)
    data['latitude_previous'] = data.groupby('vesselId')['latitude'].shift(lag_steps)
    data['longitude_previous'] = data.groupby('vesselId')['longitude'].shift(lag_steps)
    data['sog_previous'] = data.groupby('vesselId')['sog'].shift(lag_steps)
    #data['delta_lat_previous'] = data.groupby('vesselId')['delta_lat'].shift(lag_steps)
    #data['delta_lon_previous'] = data.groupby('vesselId')['delta_lon'].shift(lag_steps)
    data['cog_previous'] = data.groupby('vesselId')['cog'].shift(lag_steps)
    data['heading_previous'] = data.groupby('vesselId')['heading'].shift(lag_steps)
    data['rot_previous'] = data.groupby('vesselId')['rot'].shift(lag_steps)
    #data['close_to_port_previous'] = data.groupby('vesselId')['close_to_port'].shift(lag_steps)
    

    # Calculate time difference between consecutive points in seconds
    data['temp_time_gap'] = data.groupby('vesselId')['time'].diff(lag_steps)
    data['time_gap'] = data['temp_time_gap'].dt.total_seconds()

    # Drop any rows with missing values due to shifting or time differences
    data.dropna(inplace=True)

    data.drop(columns=['temp_time_gap'], inplace=True)

    return data

#### We make a function where we can specify amount of lags! For example, if we want to train multiple models based on different lags, as we want each model to capture different time horizons!

For instance, each vessel should apprxoimately have 240 instances for all the 5 days, i.e. we should train on 240 lags to capture all possibilities, however this reduces amount of data for the first lags (which are more important), thus we could also specify 50 lags, for example to train on the first day, nd get more data for that!

In [19]:
def create_trainingset(df, max_size=12000000, total_lags=240):
    """
    Creates a training dataset by sampling data from specified lags, with sample size per lag 
    dynamically adjusted based on the total number of lags.

    Parameters:
    - make_training_set_func (function): Function that generates the training set for a given lag.
    - max_size (int): Maximum number of total samples to accumulate across all lags.
    - total_lags (int): Total number of lag steps to include in the training dataset.

    Returns:
    - DataFrame: Concatenated training dataset containing sampled instances across specified lags.
    """
    datasets = []
    total_size = 0
    lag = 1
    
    # Dynamically calculate max_samples_per_lag based on total_lags and max_size
    max_samples_per_lag = max_size // total_lags

    while lag <= total_lags and total_size < max_size:
        # Generate dataset for the current lag
        current_set = lagged_training_data(df, lag)
        
        # If the dataset is empty for the current lag, break the loop
        if len(current_set) == 0:
            break

        # Sample the dataset with the dynamically calculated sample size for this lag
        sampled_set = current_set.sample(min(max_samples_per_lag, len(current_set)), random_state=42)
        datasets.append(sampled_set)
        total_size += len(sampled_set)

        print(f"Size after lag {lag}: {total_size:_} samples accumulated with {len(sampled_set)} samples from lag {lag}")

        # Move to the next lag step
        lag += 1

    # Concatenate all sampled datasets into a single training set
    training_data = pd.concat(datasets, ignore_index=True)
    print("Total length of training data:", len(training_data))

    # Clear out memory by deleting intermediate datasets list
    del datasets

    training_data = training_data.drop(columns=['time', 'sog', 'cog', 'heading', 'rot'])

    return training_data

In [20]:
train_data = create_trainingset(baseDataset, max_size=13000000, total_lags=14)

Size after lag 1: 871_294 samples accumulated with 871294 samples from lag 1
Size after lag 2: 1_741_904 samples accumulated with 870610 samples from lag 2
Size after lag 3: 2_611_830 samples accumulated with 869926 samples from lag 3
Size after lag 4: 3_481_072 samples accumulated with 869242 samples from lag 4
Size after lag 5: 4_349_630 samples accumulated with 868558 samples from lag 5
Size after lag 6: 5_217_504 samples accumulated with 867874 samples from lag 6
Size after lag 7: 6_084_694 samples accumulated with 867190 samples from lag 7
Size after lag 8: 6_951_200 samples accumulated with 866506 samples from lag 8
Size after lag 9: 7_817_022 samples accumulated with 865822 samples from lag 9
Size after lag 10: 8_682_160 samples accumulated with 865138 samples from lag 10
Size after lag 11: 9_546_614 samples accumulated with 864454 samples from lag 11
Size after lag 12: 10_410_384 samples accumulated with 863770 samples from lag 12
Size after lag 13: 11_273_470 samples accumulated with 863086 samples from lag 13
Size after lag 14: 12_135_872 samples accumulated with 862402 samples from lag 14
Total length of training data: 12135872

# Training pipeline!

In [21]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.multioutput import MultiOutputRegressor

# Define features (X) and targets (y)
X = train_data.drop(columns=['latitude', 'longitude'])
y = train_data[['latitude', 'longitude']]

In [22]:
# Find all DataFrames in memory
dataframes_in_memory = {name: obj for name, obj in globals().items() if isinstance(obj, pd.DataFrame)}

# Print the names and memory usage of each DataFrame
for name, df in dataframes_in_memory.items():
    print(f"{name}: {df.memory_usage(deep=True).sum() / (1024 ** 2):.2f} MB")

_: 0.00 MB
baseDataset: 66.53 MB
testset: 8.54 MB
vessels_with_low_records: 0.00 MB
ports: 0.14 MB
test_filled: 5.13 MB
_17: 0.00 MB
train_data: 1111.07 MB
X: 925.89 MB
y: 185.18 MB

In [23]:
import gc

#del gdf_with_near_land
del train_data
del testset
del baseDataset # Ikke dersom vi vil lage flere modeller for å stacke tid


# Run garbage collection to free up memory
gc.collect()

21

In [24]:
# Initialize and train the MultiOutputRegressor with RandomForest
# Initialize and train the MultiOutputRegressor with an optimized RandomForest
model = MultiOutputRegressor(
    RandomForestRegressor(
        n_estimators=20,           # Adjusted number of trees for balance between performance and training time
        n_jobs=-1,                  # Use all CPU cores dynamically
        random_state=42 ,            # For reproducibility
        warm_start=False,
        criterion='squared_error',
        max_depth=30
    )
)

model.fit(X, y)

print("Model training completed on the training dataset.")

Model training completed on the training dataset.

### Preparing test set for prediction!

In [25]:
test_filled.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51739 entries, 0 to 51738
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   ID                  51739 non-null  int64
 1   vesselId            51739 non-null  int64
 2   time                51739 non-null  datetime64[ns]
 3   cog_previous        51739 non-null  float64
 4   sog_previous        51739 non-null  float64
 5   rot_previous        51739 non-null  int64
 6   heading_previous    51739 non-null  float64
 7   latitude_previous   51739 non-null  float64
 8   longitude_previous  51739 non-null  float64
 9   close_to_port       51739 non-null  int64
 10  time_gap            51739 non-null  float64
 11  season              51739 non-null  int64
 12  is_weekend          51739 non-null  int64
dtypes: datetime64[ns](1), float64(6), int64(6)
memory usage: 5.1 MB

In [26]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12135872 entries, 0 to 12135871
Data columns (total 10 columns):
 #   Column              Dtype
---  ------              -----
 0   vesselId            int64
 1   is_weekend          int64
 2   season              int64
 3   latitude_previous   float64
 4   longitude_previous  float64
 5   sog_previous        float64
 6   cog_previous        float64
 7   heading_previous    float64
 8   rot_previous        float64
 9   time_gap            float64
dtypes: float64(7), int64(3)
memory usage: 925.9 MB

In [27]:
test_ids = test_filled['ID'].copy()
test_filled = test_filled.drop(columns=['ID'])
# Set testset columns in the same order as the training set X
testset = test_filled[X.columns]

In [28]:
def predict_and_append_coordinates(predictor, testset):
    """
    Predicts longitude and latitude for the test set using a MultiOutputRegressor model
    and appends them as new columns.

    Parameters:
    - predictor (MultiOutputRegressor): The trained model for predicting both latitude and longitude.
    - testset (pd.DataFrame): The test set including all features required for prediction.

    Returns:
    - pd.DataFrame: The test set DataFrame with appended 'latitude_predicted' and 'longitude_predicted' columns.
    """
    # Predict both latitude and longitude on the test set
    predictions = predictor.predict(testset)

    # Extract predictions for latitude and longitude
    latitude_predictions = predictions[:, 0]
    longitude_predictions = predictions[:, 1]

    # Append predictions to the test set DataFrame as new columns
    testset_with_predictions = testset.copy()
    testset_with_predictions['latitude_predicted'] = latitude_predictions
    testset_with_predictions['longitude_predicted'] = longitude_predictions

    return testset_with_predictions

# Example usage:
testset_with_predictions = predict_and_append_coordinates(model, testset)
testset_with_predictions.head(60)  # To verify the appended predictions

,vesselId,is_weekend,season,latitude_previous,longitude_previous,sog_previous,cog_previous,heading_previous,rot_previous,time_gap,latitude_predicted,longitude_predicted
0,83,0,0,31.14647,-81.49789,0.0,-0.002222,0.911111,0,900.0,31.126013,-81.488355
1,619,0,0,14.81694,120.29625,0.0,-0.862778,0.188889,0,541.0,14.755240,120.292194
2,592,0,0,38.27895,10.78280,18.7,-0.955556,-0.966667,0,654.0,38.365414,10.804020
3,538,0,0,-43.53785,172.83522,0.1,0.785000,-0.611111,0,1080.0,-43.533491,172.834818
4,1,0,0,48.53320,-6.12003,0.3,0.616667,0.527778,0,1258.0,48.495536,-6.212687
5,682,0,0,51.35306,3.19241,0.0,-0.716667,-0.716667,0,1087.0,51.399616,3.155439
6,159,0,0,43.34995,-8.50739,0.0,0.903333,0.655556,0,1077.0,43.496337,-8.674772
7,90,0,0,51.31666,3.22506,0.0,-0.913333,0.844444,0,1082.0,51.318604,3.224050
8,486,0,0,40.84712,29.29052,0.0,0.833333,0.494444,0,1083.0,40.845932,29.252883
9,174,0,0,38.47378,15.91582,0.1,0.153889,0.400000,0,1080.0,38.426787,15.915321
10,84,0,0,38.96142,-12.00502,17.1,-0.931667,-0.927778,0,996.0,39.035325,-11.984353
11,589,0,0,43.72483,-5.33660,19.7,0.538889,0.538889,-10,1080.0,43.742199,-5.439200
12,645,0,0,54.37278,18.65716,0.0,0.083333,-0.861111,0,1075.0,54.384010,18.663504
13,161,0,0,51.27275,4.21398,0.0,0.057222,0.138889,0,1080.0,51.273507,4.216574
14,240,0,0,40.66726,-74.07082,0.0,0.646667,0.661111,0,1084.0,40.660459,-74.064569
15,654,0,0,59.73643,10.23870,0.0,-0.004444,-0.005556,0,1083.0,59.732303,10.242876
16,667,0,0,-27.37772,153.16645,0.0,-0.108889,-0.788889,0,1080.0,-27.372529,153.167831
17,648,0,0,53.56397,8.56593,0.0,0.865000,-0.816667,0,1080.0,53.561416,8.560304
18,162,0,0,51.79319,3.34467,0.2,-0.760000,0.727778,0,1077.0,51.783533,3.344477
19,575,0,0,52.40704,4.86081,0.0,-0.828889,-0.800000,0,1080.0,52.421596,4.887551
20,658,0,0,53.57648,-0.09023,0.0,-0.911111,-0.483333,0,1080.0,53.579188,-0.075246
21,378,0,0,51.26926,4.21159,0.0,-0.948333,0.155556,0,1441.0,51.280618,4.218471
22,295,0,0,1.17835,103.75237,0.1,0.640556,-0.972222,0,1080.0,1.178483,103.749837
23,323,0,0,47.33692,-122.47557,0.0,0.625000,-0.350000,0,1075.0,47.334804,-122.476998
24,266,0,0,50.90418,-1.42857,0.0,0.683333,0.650000,0,1078.0,50.900542,-1.349302
25,511,0,0,51.30661,3.22715,0.0,-0.092222,-0.138889,0,1083.0,51.316290,3.225784
26,587,0,0,24.92350,-109.76272,18.9,-0.777778,-0.788889,0,1129.0,25.000754,-109.696679
27,560,0,0,40.84103,14.27640,0.0,-0.728333,-0.883333,0,1438.0,40.834325,14.276650
28,572,0,0,53.94362,10.86065,0.0,-0.899444,-0.900000,0,1081.0,53.951093,10.868739
29,576,0,0,28.14658,-15.41917,0.0,0.041667,0.511111,0,1261.0,28.146577,-15.419161
30,76,0,0,34.70981,134.84946,0.0,-0.376111,0.622222,0,1253.0,34.708351,134.848669
31,393,0,0,54.40609,18.65503,0.0,0.717778,-0.633333,0,1260.0,54.414592,18.692414
32,165,0,0,51.26723,4.21002,0.0,0.077778,0.144444,0,1260.0,51.274265,4.230330
33,175,0,0,37.53028,16.62312,16.4,0.632778,0.627778,0,1849.0,37.582499,16.502679
34,571,0,0,53.94312,10.86149,0.0,-0.891111,-0.900000,0,1261.0,53.966026,10.872928
35,81,0,0,56.15072,10.23467,0.0,-0.175000,-0.772222,0,1261.0,56.150566,10.253625
36,245,0,0,53.57480,8.55801,0.0,-0.474444,0.344444,0,1264.0,53.571619,8.554310
37,23,0,0,6.03446,116.08002,0.1,0.961111,0.194444,0,1260.0,6.034286,116.079997
38,271,0,0,53.57839,8.55239,0.0,0.942222,-0.977778,0,1263.0,53.577184,8.551943
39,397,0,0,53.58649,-0.06694,0.0,0.533889,-0.422222,0,1259.0,53.570136,-0.026480
40,513,0,0,43.34959,5.33275,0.0,-0.861667,0.711111,0,1260.0,43.347770,5.381237
41,329,0,0,18.83830,-73.38830,12.0,0.855556,0.855556,0,1133.0,18.890116,-73.435885
42,636,0,0,54.68123,-0.76436,13.6,-0.240000,-0.244444,-7,1158.0,54.631959,-0.676740
43,601,0,0,43.58091,10.30402,0.0,0.958333,-0.038889,0,1265.0,43.570537,10.207553
44,132,0,0,10.63966,106.76221,0.0,-0.368889,-0.372222,0,1119.0,10.616501,106.764303
45,638,0,0,47.26898,-122.41612,0.0,-0.922778,0.766667,0,1260.0,47.271160,-122.414148
46,417,0,0,-27.37955,153.16483,0.0,0.683333,-0.788889,0,1260.0,-27.350971,153.174731
47,478,0,0,29.86279,-93.93649,0.0,0.461111,0.222222,0,1260.0,29.867765,-93.928618
48,363,0,0,53.53161,9.99845,0.0,-0.505556,0.738889,0,1259.0,53.538180,9.989817
49,116,0,0,51.29873,3.23363,0.0,-0.136667,-0.155556,0,1255.0,51.315646,3.232185
50,200,0,0,37.34931,16.29756,18.6,0.216667,0.216667,-8,1147.0,37.289657,16.219348
51,483,0,0,51.29938,3.23925,0.0,0.927778,0.850000,0,1260.0,51.310102,3.224577
52,62,0,0,36.69340,-4.38806,0.1,-0.287222,-0.800000,0,1264.0,36.693110,-4.379433
53,350,0,0,50.63193,-1.01217,0.0,0.094444,-0.644444,0,1265.0,50.631729,-1.003329
54,646,0,0,47.54429,-122.52558,0.2,0.860000,-0.794444,0,1256.0,47.543727,-122.522736
55,71,0,0,-32.04416,115.75027,0.0,0.470556,-0.783333,-1,1262.0,-32.043197,115.731532
56,657,0,0,-43.42598,173.05472,17.4,0.261667,0.266667,0,1174.0,-43.480461,173.006663
57,282,0,0,58.01013,11.70418,0.0,0.094444,0.566667,0,1260.0,57.976941,11.707063
58,550,0,0,39.44153,-0.30527,0.0,-0.542222,0.994444,0,1258.0,39.432813,-0.280532
59,611,0,0,40.71220,29.46757,0.0,-0.221667,0.700000,0,1442.0,40.717719,29.440444

In [29]:
def predict_and_prepare_submission(predictor, testset, test_ids, submission_path='submission.csv'):
    """
    Predicts latitude and longitude for the test set using a MultiOutputRegressor model, 
    merges the predictions with test IDs, and creates a submission file in the required Kaggle format.

    Parameters:
    - predictor (MultiOutputRegressor): The trained model for predicting both latitude and longitude.
    - testset (pd.DataFrame): The test set including all features required for prediction.
    - test_ids (pd.Series or list): The IDs for each entry in the test set.
    - submission_path (str): The path to save the submission CSV file.

    Returns:
    - pd.DataFrame: The final submission dataframe.
    """
    # Step 1: Predict both latitude and longitude on the test set
    predictions = predictor.predict(testset)

    # Step 2: Extract latitude and longitude predictions
    latitude_predictions = predictions[:, 0]
    longitude_predictions = predictions[:, 1]

    # Step 3: Combine predictions with test IDs into a single DataFrame
    submission_df = pd.DataFrame({
        'ID': test_ids,
        'longitude_predicted': longitude_predictions,
        'latitude_predicted': latitude_predictions
    })

    # Step 4: Save to CSV with the correct column order
    submission_df.to_csv(submission_path, index=False, columns=['ID', 'longitude_predicted', 'latitude_predicted'])
    print(f"Submission file saved to {submission_path}")

    return submission_df

# Example usage:
submission_df = predict_and_prepare_submission(model, testset, test_ids, '../../submissions/temporal-20estimators-14lags.csv')
submission_df.head(50)  # To verify the structure of the submission file

Submission file saved to ../../submissions/temporal-20estimators-14lags.csv

    ID  longitude_predicted  latitude_predicted
0    0           -81.488355           31.126013
1    1           120.292193           14.755239
2    2            10.804019           38.365414
3    3           172.834818          -43.533491
4    4            -6.212687           48.495536
5    5             3.155439           51.399616
6    6            -8.674772           43.496337
7    7             3.224050           51.318604
8    8            29.252883           40.845932
9    9            15.915321           38.426787
10  10           -11.984353           39.035325
11  11            -5.439200           43.742199
12  12            18.663504           54.384010
13  13             4.216574           51.273507
14  14           -74.064569           40.660459
15  15            10.242876           59.732303
16  16           153.167831          -27.372529
17  17             8.560304           53.561416
18  18             3.344477           51.783533
19  19             4.887551           52.421596
20  20            -0.075246           53.579188
21  21             4.218471           51.280618
22  22           103.749837            1.178483
23  23          -122.476998           47.334804
24  24            -1.349302           50.900542
25  25             3.225784           51.316290
26  26          -109.696679           25.000754
27  27            14.276650           40.834325
28  28            10.868739           53.951093
29  29           -15.419161           28.146577
30  30           134.848669           34.708351
31  31            18.692414           54.414591
32  32             4.230330           51.274265
33  33            16.502679           37.582499
34  34            10.872928           53.966026
35  35            10.253625           56.150566
36  36             8.554310           53.571619
37  37           116.079997            6.034286
38  38             8.551943           53.577184
39  39            -0.026480           53.570136
40  40             5.381237           43.347770
41  41           -73.435885           18.890116
42  42            -0.676740           54.631959
43  43            10.207553           43.570537
44  44           106.764303           10.616501
45  45          -122.414148           47.271160
46  46           153.174731          -27.350971
47  47           -93.928618           29.867765
48  48             9.989817           53.538179
49  49             3.232185           51.315646

In [30]:
X.columns

Index(['vesselId', 'is_weekend', 'season', 'latitude_previous',
       'longitude_previous', 'sog_previous', 'cog_previous',
       'heading_previous', 'rot_previous', 'time_gap'],
      dtype='object')

In [31]:
# Get feature importances for each target
for i, estimator in enumerate(model.estimators_):
    print(f"Feature importances for target {i}: {estimator.feature_importances_}")

Feature importances for target 0: [4.50638255e-03 3.40967026e-04 4.71460231e-04 9.47510393e-01
 8.35081822e-03 1.78628967e-03 2.19825855e-03 2.41491015e-03
 1.98614395e-04 3.22219060e-02]
Feature importances for target 1: [2.26138557e-03 1.18320738e-04 1.79402062e-04 6.49998499e-03
 9.47995655e-01 9.19296114e-04 1.35587760e-03 1.34677800e-03
 1.35853478e-04 3.91874461e-02]